---
- hosts: all
  become: true
  tasks:
    - name: update packages
      apt:
        update_cache: true

    - name: changes root password
      user:
        name: root
        update_password: always
        password: Alma1234

    - name: add debian to sudo group
      user:
        name: debian
        groups: sudo
        append: true

    - name: install mc
      apt:
        name: mc
        state: present

    - name: install htop
      apt:
        name: htop
        state: present

    - name: install OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present

    - name: create udemx user
      user:
        name: udemx
        createhome: true
        home: /opt/udemx
        password: "udemx"

    - name: install openssh server
      apt:
        name: openssh-server
        state: present

    - name: change ssh port and enable root login
      replace:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      loop:
        - regexp: '#Port 22'
          replace: 'Port 2222'
        - regexp: '#PermitRootLogin prohibit-password'
          replace: 'PermitRootLogin yes'

    - name: install fail2ban
      apt:
        name: fail2ban
        state: present
      notify:
        - Restart fail2ban
      tags:
        - fail2ban

    - name: create jail.local file
      file:
        path: /etc/fail2ban/jail.local
        state: touch
        mode: 0644

    - name: copy fail2ban jail config file
      fetch:
        src: /etc/fail2ban/jail.conf
        dest: /etc/fail2ban/jail.local

    - name: config fail2ban ssh jail
      replace:
        path: /etc/fail2ban/jail.local
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      loop:
        - regexp: '# [sshd]'
          replace: '[sshd]'
        - regexp: '# enabled = true'
          replace: 'enabled = true'

    - name: config fail2ban nginx-http-auth
      lineinfile:
        path: /etc/fail2ban/jail.local
        insertafter: "[nginx-http-auth]"
        line: "enabled = true"

    - name: install packages
      become: true
      become_user: root
      apt:
        state: present
        name:
          - mariadb-server
          - git
          - iptables
          - curl
          - gnupg

    - name: ensure the jenkins apt repository key is installed
      get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

    - name: ensure the repository is configured
      apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian binary/'
        state: present
      become: true

    - name: ensure jenkins is installed
      apt: name=jenkins update_cache=yes
      become: true

    - name: ensure jenkins is running
      service: name=jenkins state=started

  handlers:
    - name: Restart fail2ban
      service:
        name: fail2ban
        state: restarted
