---
- hosts: all
  become: true
  tasks:
    - name: update packages
      apt:
        update_cache: true

    - name: changes root password
      user:
        name: root
        update_password: always
        password: Alma1234

    - name: add debian to sudo group
      user:
        name: debian
        groups: sudo
        append: true

    - name: install mc
      apt:
        name: mc
        state: present

    - name: install htop
      apt:
        name: htop
        state: present

    - name: install OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present

    - name: create udemx user
      user:
        name: udemx
        createhome: true
        home: /opt/udemx
        password: "udemx"

    - name: install openssh server
      apt:
        name: openssh-server
        state: present

    - name: change ssh port and enable root login
      replace:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      loop:
        - regexp: '#Port 22'
          replace: 'Port 2222'
        - regexp: '#PermitRootLogin prohibit-password'
          replace: 'PermitRootLogin yes'

    - name: Install fail2ban
      apt:
        name: fail2ban
        state: present
      when: ansible_os_family == 'Debian'
      become: true

    - name: Start fail2ban service
      service:
        name: fail2ban
        state: started
      become: true

    - name: Enable fail2ban service
      service:
        name: fail2ban
        enabled: true
      become: true

    - name: copy fail2ban jail config file
      copy:
        src: /etc/fail2ban/jail.conf
        dest: /etc/fail2ban/jail.local
        mode: 0755
        remote_src: true

    - name: config fail2ban ssh jail
      replace:
        path: /etc/fail2ban/jail.local
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      loop:
        - regexp: '# [sshd]'
          replace: '[sshd]'
        - regexp: '# enabled = true'
          replace: 'enabled = true'

    - name: Restart fail2ban service
      service:
        name: fail2ban
        state: restarted

    - name: install packages
      become: true
      become_user: root
      apt:
        state: present
        name:
          - mariadb-server
          - git
          - iptables
          - curl
          - gnupg
          - python3-pip

    - name: ensure nginx is present
      apt:
        name: nginx
        state: present

    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Start Hello World Docker container
      community.docker.docker_container:
        image: hello-world
        name: hello-world
        state: started

    - name: setup git name
      become_user: udemx
      become: true
      git_config:
        name: user.name
        scope: global
        value: "udemx"

    - name: setup git user email
      git_config:
        name: user.email
        scope: global
        value: udemx@udemx.eu

    - name: ensure the jenkins apt repository key is installed
      become: true
      become_user: root
      get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

    - name: jenkins public key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 5BA31D57EF5975CA

    - name: ensure the repository is configured
      apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian binary/'
        state: present
      become: true

    - name: ensure jenkins is installed
      apt: name=jenkins update_cache=yes
      become: true

    - name: ensure jenkins is running
      service: name=jenkins state=started
