---
- hosts: all
  become: true
  tasks:
    - name: install packages
      become: true
      become_user: root
      apt:
        state: present
        name:
          - mariadb-server
          - git
          - iptables
          - curl
          - gnupg

    - name: ensure the jenkins apt repository key is installed
      get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

    - name: ensure the repository is configured
      apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian binary/'
        state: present
      become: true

    - name: ensure jenkins is installed
      apt: name=jenkins update_cache=yes
      become: true

    - name: ensure jenkins is running
      service: name=jenkins state=started
